spring:
  application:
    name: gestion-commandes

  datasource:
    url: jdbc:mysql://localhost:3306/gestion_commande?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: da
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

# Configuration Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.polytech.commandes.controller
  paths-to-match: /api/**

logging:
  level:
    com.polytech.commandes: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# Configuration JWT
application:
  security:
    jwt:
      secret-key: Itw6ky5tkqmBRkKxcTsLpcOgf0XdsicegbGynptlqqU=
      expiration: 86400000  # 24 heures

